# docker-compose to deploy website monitoring tool in production

version: "3.8"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: changeme
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: # Enable server reload on code changes
      - ./api:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DOCKER: "true"
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: url-shortener_db_1
      DB_PASSWORD: changeme
      JWT_SECRET_KEY: changemeeeeee
      OAUTH_SERVER: https://auth.viarezo.fr
      OAUTH_AUTHORIZATION_URL: /oauth/authorize
      OAUTH_TOKEN_URL: /oauth/token
      OAUTH_USERINFO_URL: /api/user/show/me
      OAUTH_REDIRECT_URI: http://localhost:8000/auth/login
      OAUTH_CLIENT_ID: change
      OAUTH_CLIENT_SECRET: change
      OAUTH_SCOPE: default
      TZ: Europe/Paris
    restart: always
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=changeme
      - DOCKER_INFLUXDB_INIT_ORG=viarezo
      - DOCKER_INFLUXDB_INIT_BUCKET=urlshortener
      - DOCKER_INFLUXDB_INIT_RETENTION=52w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=aaaa
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=influxdb
      - INFLUXDB_PASSWORD=changeme
volumes:
  influxdb-storage:
  chronograf-storage:
