# docker-compose to deploy website monitoring tool in production

version: "3.8"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: changeme
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: # Enable server reload on code changes
      - ./api:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DOCKER: "true"
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: url-shortener_db_1
      DB_PASSWORD: changeme
      TZ: Europe/Paris
    restart: always
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=influxdb
      - INFLUXDB_ADMIN_PASSWORD=changeme
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=influxdb
      - INFLUXDB_PASSWORD=changeme
volumes:
  influxdb-storage:
  chronograf-storage:
