# docker-compose to deploy website monitoring tool in production

version: "3.8"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: changeme
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes: # Enable server reload on code changes
      - ./api:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DOCKER: "true"
      DB_USER: postgres
      DB_NAME: postgres
      DB_HOST: website-monitoring-tool_db_1
      DB_PASSWORD: changeme
      TZ: Europe/Paris
    restart: always
